name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #.... for routing
  go_router: ^14.3.0
  fpdart: ^1.1.1
  supabase_flutter: ^2.8.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
  
